version: '3.1'

services:
  jrtb-db:
    image: mysql
    restart: always
    container_name: dev-jrtb-db
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: "dev_jrtb_db"
      MYSQL_ROOT_PASSWORD: root